version: "3"

services:
  mongo-container:
    image: mongo:4.2
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    restart: always

  mysql-container:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bonsae-import
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d