version: "3.8"

services:
  mongo-container:
    image: mongo:4.2
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"

  mysql-container:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bonsae_import_db
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  api-container:
    build: .
    container_name: api-container
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - MONGO_URL=mongodb://admin:pass@mongo-db:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.0.0
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=bonsae_import_db
    depends_on:
      - mongo-container
      - mysql-container