import { Model, DataTypes } from 'sequelize';
import { sequelize } from '../../connection/mysql.js';

export class User extends Model {}

User.init({
  id: {
    type: DataTypes.BIGINT.UNSIGNED,
    primaryKey: true,
    autoIncrement: true,
  },
  id_old_bonsae: DataTypes.INTEGER,
  id_audora: DataTypes.INTEGER,
  profile_id: DataTypes.INTEGER.UNSIGNED,
  active: DataTypes.CHAR,
  name: DataTypes.STRING,
  registration_number: DataTypes.STRING,
  email: DataTypes.STRING,
  receive_emails: DataTypes.TINYINT,
  gmail: DataTypes.STRING,
  gcalendar_credentials: DataTypes.STRING,
  approve_api: DataTypes.CHAR,
  approve_msg: DataTypes.STRING,
  telephone: DataTypes.STRING,
  password: DataTypes.STRING,
  cpf: DataTypes.STRING,
  period_id: DataTypes.INTEGER,
  oab: DataTypes.STRING,
  oab_uf: DataTypes.STRING,
  workload_real: DataTypes.TIME,
  workload_simulated: DataTypes.TIME,
  observations: DataTypes.TEXT,
  profile_pic: DataTypes.STRING,
  course: DataTypes.STRING,
  course_id: DataTypes.INTEGER,
  is_admin: DataTypes.CHAR,
  remember_token: DataTypes.STRING,
  access_token: DataTypes.STRING,
  browser_agent: DataTypes.STRING,
  date_accept: DataTypes.DATE,
  last_login: DataTypes.DATE,
  last_logout: DataTypes.DATE,
  logged_time: DataTypes.TIME,
  all_time_logged: DataTypes.TIME,
  average_logged_time: DataTypes.TIME,
  times_active: DataTypes.INTEGER,
  ip: DataTypes.STRING,
  permission: DataTypes.TINYINT,
  integration: DataTypes.STRING,
  created_at: DataTypes.DATE,
  updated_at: DataTypes.DATE,
  deleted_at: DataTypes.DATE,
}, {
  sequelize,
  modelName: 'User',
  tableName: 'users',
  timestamps: false,
  paranoid: true,
  underscored: true,
});
